export const BUTTON_VARIANTS = {
  TOGGLE: [
    "flex-1",
    "cursor-pointer",
    "relative",
    "rounded-[1.5rem]",
    "font-semibold",
    "mx-1",
    "py-[0.4rem]",
    "leading-[1.4]",
    "text-center",
    "text-sm",
    "backdrop-blur-none",
    "bg-transparent",
    "shadow-none",
    "border-none",
    "outline-none",
  ].join(" "),
  MY_PAGE_BUTTON: [
    "w-108",
    "h-14",
    "bg-gradient-to-r",
    "from-[#f43f5e] to-[#f59e42]",
    "text-white",
    "rounded-[1.2rem]",
    "py-[0.9rem]",
    "px-10",
    "font-bold",
    "text-[1.15rem]",
    "border-none",
    "shadow-[0_2px_12px_rgba(244,63,94,0.13)]",
    "transition-all",
    "duration-300",
    "hover:bg-[#d32f2f]",
    "hover:shadow-[0_6px_24px_rgba(244,63,94,0.21)]",
  ].join(" "),
  ICON: [""],
  PAGINATION: [
    "h-8",
    "w-8",
    "cursor-pointer",
    "rounded-sm",
    "text-black-200",
  ].join(" "),
  MUSIC_CARD: [
    "w-44",
    "overflow-hidden",
    "whitespace-nowrap",
    "bg-[linear-gradient(45deg,#6366f1,#8b5cf6,#ec4899,#f59e0b)]",
    "bg-clip-text",
    "text-transparent",
    "bg-white/90",
    "backdrop-blur-[12px]",
    "border",
    "border-[rgba(99,102,241,0.2)]",
    "shadow-[0_8px_24px_rgba(99,102,241,0.15)]",
    "rounded-[8px]",
    "text-sm",
    "font-bold",
  ].join(" "),
  LOGIN_BUTTON: [
    "relative",
    "flex",
    "w-full",
    "items-center",
    "justify-center",
    "gap-2.5",
    "rounded-lg",
    "border",
    "border-[#747775]",
    "bg-white",
    "pl-3",
    "pr-3",
    "py-3",
    "text-sm",
    "font-medium",
    "text-[#1F1F1F]",
    "shadow-sm",
    "hover:bg-gray-50",
    "transition-colors",
  ].join(" "),
  FLOATING_TOGGLE: [
    "flex",
    "items-center",
    "gap-2.5",
    "rounded-full",
    "px-4",
    "py-3",
    "border",
    "border-gray-200/80",
    "bg-white/95",
    "backdrop-blur-md",
    "shadow-lg",
    "shadow-gray-900/10",
    "hover:scale-105",
    "hover:shadow-xl",
    "hover:shadow-gray-900/15",
    "hover:border-gray-300",
    "active:scale-100",
    "transition-all",
    "duration-200",
    "ease-out",
    "text-sm",
    "font-semibold",
    "text-gray-700",
  ].join(" "),
  ICON_BUTTON: [
    "rounded-full",
    "p-2",
    "hover:bg-gray-100",
    "transition-colors",
  ].join(" "),
  MENU_ITEM: [
    "flex",
    "items-center",
    "gap-3",
    "rounded-lg",
    "px-4",
    "py-3",
    "text-left",
    "text-gray-700",
    "transition-colors",
    "hover:bg-gray-100",
  ].join(" "),
  FLOATING_TOGGLE_EXPAND: [
    "h-14",
    "w-14",
    "rounded-full",
    "bg-gradient-to-br",
    "from-indigo-500",
    "via-purple-500",
    "to-pink-500",
    "shadow-lg",
    "shadow-indigo-500/30",
    "hover:shadow-xl",
    "hover:shadow-indigo-500/40",
    "hover:scale-110",
    "active:scale-95",
    "flex",
    "items-center",
    "justify-center",
    "transition-all",
    "duration-300",
    "ease-out",
    "text-white",
  ].join(" "),
  EDIT_BUTTON: [
    "rounded",
    "px-2",
    "py-1",
    "text-xs",
    "font-medium",
    "text-white",
    "transition-colors",
    "hover:bg-blue-500",
  ].join(" "),
  DELETE_BUTTON: [
    "rounded",
    "px-2",
    "py-1",
    "text-xs",
    "font-medium",
    "text-white",
    "transition-colors",
    "hover:bg-red-500",
  ].join(" "),
  SUBMIT_BUTTON: [
    "flex-1",
    "rounded-lg",
    "bg-linear-to-r",
    "from-blue-500",
    "to-purple-600",
    "px-6",
    "py-3",
    "font-semibold",
    "text-white",
    "shadow-lg",
    "transition-all",
    "hover:from-blue-600",
    "hover:to-purple-700",
    "hover:shadow-xl",
    "disabled:cursor-not-allowed",
    "disabled:opacity-50",
  ].join(" "),
  CANCEL_BUTTON: [
    "rounded-lg",
    "border",
    "border-gray-300",
    "bg-white",
    "px-6",
    "py-3",
    "font-semibold",
    "text-gray-700",
    "transition-all",
    "hover:bg-gray-50",
  ].join(" "),
  MODAL_CLOSE: [
    "absolute",
    "top-4",
    "right-4",
    "rounded-full",
    "p-2",
    "text-gray-400",
    "hover:bg-gray-100",
    "hover:text-gray-600",
    "transition-colors",
  ].join(" "),
  TOGGLE_BUTTON: [
    "flex",
    "h-12",
    "w-12",
    "cursor-pointer",
    "items-center",
    "justify-center",
    "rounded-full",
    "bg-gradient-to-br",
    "text-white",
    "shadow-lg",
    "transition-all",
    "duration-300",
    "hover:scale-110",
    "hover:shadow-xl",
    "ring-4",
    "ring-white/50",
  ].join(" "),
  LOGIN_METHOD_BUTTON: [
    "flex-1",
    "rounded-lg",
    "px-4",
    "py-2",
    "text-sm",
    "font-medium",
    "transition-all",
  ].join(" "),
} as const;

export const DEFAULT_BUTTON_VARIANT = "TOGGLE";

export type ButtonVariant = keyof typeof BUTTON_VARIANTS;
